version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DATABASE_ATLAS=mongodb+srv://mulersoft:Linger1221@muziccluster.vtmuf.mongodb.net/messageHub
    volumes:
      - ./backend:/usr/src/app
    networks:
      - messagehub-network

networks:
  messagehub-network:
    driver: bridge
